apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
  namespace: test

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
  storageClassName: local-storage
